USE DISCIPLINA02
GO

--DROP TABLE FUNCIONARIOS;

--1) CRIE UMA TABELA DE NOME FUNCIONARIOS COM OS SEGUINTES CAMPOS
/*
	IDFUNCIONARIO INTEIRO OBRIGATÓRIO AUTOINCREMENTO INICIANDO EM 1 E INCREMENTO DE 1
	NOME ATÉ 100 CARACTERES OBRIGATÓRIO
	RG ATÉ 9 CARACTERES OBRIGATÓRIO
	UF DO RG, OBRIGATÓRIO
	CPF 11 CARACTERES, OBRIGATÓRIO, ÚNICO
	DT_CONTRATACAO DATA E HORA, OBRIGATÓRIO
	DT_DEMISSAO DATA E HORA, OPCIONAL
	LOGRADOURO OBRIGATÓRIO

	IDFUNCIONÁRIO É A CHAVE PRIMÁRIA
	O PAR RG E UF DO RG É ÚNICO
*/

CREATE TABLE FUNCIONARIOS(
	IDFUNCIONARIO INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	RG CHAR(9) NOT NULL,
	IDUF_RG INT NOT NULL,
	CPF CHAR(11) NOT NULL,
	DT_CONTRATACAO DATETIME NOT NULL,
	DT_DEMISSAO DATETIME NULL,
	IDLOGRADOURO INT NOT NULL,

	CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY(IDFUNCIONARIO),
	CONSTRAINT UNQ_FUNCIONARIOS_CPF UNIQUE(CPF),
	CONSTRAINT UNQ_FUNCIONARIOS_RG_ID_UF_RG UNIQUE(RG,IDUF_RG),
	CONSTRAINT FK_FUNCIONARIOS_UFS FOREIGN KEY(IDUF_RG)
	REFERENCES UFS(IDUF),
	CONSTRAINT FK_FUNCIONARIOS_LOGRADOUROS FOREIGN KEY(IDLOGRADOURO)
	REFERENCES LOGRADOUROS(IDLOGRADOURO)
);


INSERT INTO FUNCIONARIOS
(NOME, RG, IDUF_RG, CPF, DT_CONTRATACAO, DT_DEMISSAO, IDLOGRADOURO)
VALUES
('FULANO', '111111111', 5, '11111111111', '20160120', NULL, 1),('BELTRANO', '222222222', 7, '22222222222', '20150301', NULL, 2),
('TRAJANO', '333333333', 27, '33333333333', '20150630', NULL, 3), ('ALUNO', '444444444', 9, '44444444444', '20141201', NULL, 4);