USE DISCIPLINA02
GO

--1) CRIE UMA PROCEDURE QUE RECEBA O ID DE UMA CIDADE E O ID DE UMA UF E ALTERE ESSA CIDADE PARA A UF INFORMADA

CREATE PROCEDURE USP_ALTERA_UF_CIDADE(@IDCIDADE INT, @IDUF INT)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE CIDADES
		SET IDUF = @IDUF
	WHERE IDCIDADE = @IDCIDADE;
END;

--2) CRIE UMA PROCEDURE QUE RECEBA O CPF DE UM FUNCIONARIO E ATUALIZE SUA DATA DE DEMISSAO PARA O MOMENTO DA EXECUÇÃO DA PROCEDURE

CREATE PROCEDURE USP_DEMITE_FUNCIONARIO(@CPF CHAR(11))
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE FUNCIONARIOS
	SET DT_DEMISSAO = GETDATE()
	WHERE CPF = @CPF;
END;

--3) CRIE UMA PROCEDURE QUE RECEBA UMA PORCENTAGEM (INTEIRA) E DIMINUA O VALOR DE TODOS OS PRODUTOS DE ACORDO COM A PORCENTAGEM INFORMADA

CREATE PROCEDURE USP_PROMOCAO(@PORCENTAGEM INT)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE PRODUTOS
	--SET VALOR = VALOR - ((VALOR * @PORCENTAGEM)/100)
	SET VALOR = VALOR - (VALOR * (@PORCENTAGEM/100.0))
END;


--4) CRIE UMA PROCEDURE QUE RECEBA UM IDCLIENTE E UMA DATA E REMOVA TODAS OS ITENS VENDAS DAS VENDAS DESSE CLIENTE NESTA DATA

CREATE PROCEDURE USP_REMOVE_ITENS_VENDAS(@IDCLIENTE INT, @DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM ITENS_VENDAS
	WHERE EXISTS(
		SELECT 1
		FROM VENDAS V
		WHERE V.IDVENDA = ITENS_VENDAS.IDVENDA
		AND V.IDCLIENTE = @IDCLIENTE
		AND V.DATA = @DATA
	)
END;

ALTER PROCEDURE USP_REMOVE_ITENS_VENDAS(@IDCLIENTE INT, @DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON;

	DELETE ITENS_VENDAS
	FROM ITENS_VENDAS IV
	INNER JOIN VENDAS V ON (V.IDVENDA = IV.IDVENDA)
	WHERE V.IDCLIENTE = @IDCLIENTE
	AND V.DATA = @DATA
END;
GO

ALTER PROCEDURE USP_REMOVE_ITENS_VENDAS(@IDCLIENTE INT, @DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON;

	DELETE ITENS_VENDAS
	FROM ITENS_VENDAS IV
	INNER JOIN VENDAS V ON (V.IDVENDA = IV.IDVENDA)
	WHERE V.IDCLIENTE = @IDCLIENTE
	AND V.DATA >= @DATA AND V.DATA < @DATA+1
END;
GO

--5) CRIE UMA PROCEDURE QUE RECEBA UM IDCLIENTE E UMA DATA E REMOVA TODAS VENDAS DESSE CLIENTE NESTA DATA

CREATE PROCEDURE USP_REMOVE_VENDAS(@IDCLIENTE INT, @DATA DATETIME)
AS
BEGIN
	SET NOCOUNT ON;

	EXEC USP_REMOVE_ITENS_VENDAS @IDCLIENTE, @DATA;

	DELETE FROM VENDAS
	WHERE IDCLIENTE = @IDCLIENTE
	AND DATA = @DATA;
END;