USE DISCIPLINA02
GO


--1) INCREMENTE EM 1% O VALOR DE TODOS OS ITENS_VENDAS RELACIONADOS A PRODUTOS CUJO NOME INICIA COM A LETRA "A".

--2) AUMENTE EM 2 DIAS A DATA DE TODAS AS VENDAS DE CLIENTES NASCIDOS NA PB


/*
3) INSIRA NOVAMENTE NA TABELA PRODUTOS OS PRODUTOS CUJO VALOR SEJA MENOR QUE 50, COM UM NOVO ID (QUE É GERADO AUTOMATICAMENTE) 
E COM O VALOR SENDO O DOBRO DO VALOR ANTIGO.
*/


--4) CRIE UMA NOVA TABELA CHAMADA "PRODUTOS_DUPLICADOS" COM OS PRODUTOS CUJO NOME APARECE MAIS DE UMA VEZ, AUMENTANDO SEU VALOR EM 3%



--5) REMOVA TODOS OS PRODUTOS CUJO NOME SEJA REPETIDO, REMOVENDO SEMPRE AQUELE CUJO IDPRODUTO SEJA MAIOR


/*
6) BASEADO NA TABELA "PRODUTOS_DUPLICADOS", ATUALIZE O VALOR DOS PRODUTOS DA SEGUINTE FORMA:
OS PRODUTOS COM MESMO NOME, IGUALAR AO VALOR DE PRODUTOS_DUPLICADOS
OS DEMAIS, AUMENTAR O VALOR EM 2%
*/


--7) CRIE UMA VIEW QUE EXIBA O NOME DO CLIENTE E O VALOR MEDIO DE SUAS COMPRAS



--8) CRIE UMA VIEW QUE EXIBA O NOME DO PRODUTO, A DATA DA PRIMEIRA VEZ E DA ÚLTIMA VEZ QUE FOI COMPRADO



--9) CRIE UMA FUNÇÃO QUE RECEBA UMA SIGLA DE ESTADO E RETORNE O NÚMERO DE MUNICÍPIOS DO MESMO


/*
10) ADICIONE A COLUNA DT_ULTIMA_COMPRA NA TABELA CLIENTES, DO TIPO DATETIME E PODENDO TER VALOR NULO.
AGORA CRIE UMA TRIGGER NA TABELA VENDAS QUE, SEMPRE QUE UM CLIENTE FIZER UMA COMPRA (VENDA), ESTA ATUALIZE A DT_ULTIMA_COMPRA COM A DATA DA MESMA.
*/
