USE DISCIPLINA02
GO

-- 1) CRIE UMA PROCEDURE QUE RECEBA O ID DE UMA CIDADE E O ID DE UMA UF E ALTERE ESSA CIDADE PARA A UF INFORMADA


-- 2) CRIE UMA PROCEDURE QUE RECEBA O CPF DE UM FUNCIONARIO E ATUALIZE SUA DATA DE DEMISSAO PARA O MOMENTO DA EXECU��O DA PROCEDURE


-- 3) CRIE UMA PROCEDURE QUE RECEBA UMA PORCENTAGEM (INTEIRA) E DIMINUA O VALOR DE TODOS OS PRODUTOS DE ACORDO COM A PORCENTAGEM INFORMADA


-- 4) CRIE UMA PROCEDURE QUE RECEBA UM IDCLIENTE E UMA DATA E REMOVA TODAS OS ITENS VENDAS DAS VENDAS DESSE CLIENTE NESTA DATA

-- 5) CRIE UMA PROCEDURE QUE RECEBA UM IDCLIENTE E UMA DATA E REMOVA TODAS VENDAS DESSE CLIENTE NESTA DATA

