# -*- coding: utf-8 -*-
"""Análise de Turnover em Departamento de Desenvolvimento.ipynb

Automatically generated by Colaboratory.

Original file is located at:
    https://colab.research.google.com/drive/1Oq3qQ3_7V4kK4JX4Hj7v4X4Z4X4Z4X4Z
"""

# Importação de bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from scipy.stats import chi2_contingency, ttest_ind

# Configuração de visualização
plt.style.use('ggplot')
sns.set_palette("husl")
#%matplotlib inline

# 1. Carregamento e Inspeção Inicial dos Dados
try:
    df = pd.read_csv('dados_rh.csv')
    print("✅ Arquivo carregado com sucesso!")
except FileNotFoundError:
    print("❌ Arquivo não encontrado!")

# Função para análise preliminar
def initial_analysis(df):
    print("\n🔍 Dimensões do Dataset:", df.shape)
    print("\n📋 Primeiras linhas:")
    print(df.head(2))
    
    print("\n🔧 Estrutura do Dataset:")
    print(df.info())
    
    print("\n🧮 Estatísticas Descritivas:")
    print(df.describe(include='all').T)
    
    print("\n🔎 Valores Faltantes:")
    missing = df.isnull().sum()
    print(missing[missing > 0])
    input("\nPressione ENTER para continuar..")

initial_analysis(df.copy())

# 2. Pré-processamento e Engenharia de Features
def preprocess_data(df):
    # Converter variáveis categóricas
    le = LabelEncoder()
    categorical_cols = df.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        df[col] = le.fit_transform(df[col].astype(str))
    
    # Criar variável target binária
    df['Left'] = df['Status'].apply(lambda x: 1 if x == 'Desligado' else 0)
    
    return df

df_processed = preprocess_data(df.copy())

# 3. Análise do Turnover
def turnover_analysis(df):
    # Taxa de turnover geral
    turnover_rate = df['Left'].mean()
    print(f"\n💼 Taxa de Turnover Geral: {turnover_rate:.2%}")
    
    # Taxa por departamento
    if 'Departamento' in df:
        dept_turnover = df.groupby('Departamento')['Left'].mean()
        print("\n📊 Taxa de Turnover por Departamento:")
        (dept_turnover)
    
    # Análise temporal
    plt.figure(figsize=(10,6))
    sns.kdeplot(df[df['Left']==0]['Tempo de Empresa'], label='Ativos')
    sns.kdeplot(df[df['Left']==1]['Tempo de Empresa'], label='Desligados')
    plt.title('Distribuição do Tempo de Empresa')
    plt.legend()
    plt.show()

turnover_analysis(df_processed.copy())

# 4. Análise de Fatores-Chave
def key_factor_analysis(df):
    # Selecionar variáveis relevantes
    factors = ['Idade', 'Banda Salarial', 'Engajamento', 'Satisfação',
               'Apoio da Liderança', 'Percepção de Desenvolvimento',
               'Horas-extras (média)', 'Última Promoção (anos)']
    
    # Teste estatístico para cada variável
    print("\n🔬 Significância Estatística dos Fatores:")
    for factor in factors:
        active = df[df['Left']==0][factor]
        left = df[df['Left']==1][factor]
        t_stat, p_val = ttest_ind(active, left, nan_policy='omit')
        print(f"{factor}: p-value = {p_val:.4f}")

    # Visualização dos principais fatores
    plt.figure(figsize=(15,10))
    
    plt.subplot(2,2,1)
    sns.boxplot(x='Left', y='Apoio da Liderança', data=df)
    plt.title('Apoio da Liderança vs Turnover')
    
    plt.subplot(2,2,2)
    sns.boxplot(x='Left', y='Percepção de Desenvolvimento', data=df)
    plt.title('Percepção de Desenvolvimento vs Turnover')
    
    plt.subplot(2,2,3)
    sns.boxplot(x='Left', y='Última Promoção (anos)', data=df)
    plt.title('Tempo desde Última Promoção vs Turnover')
    
    plt.subplot(2,2,4)
    sns.boxplot(x='Left', y='Horas-extras (média)', data=df)
    plt.title('Horas Extras vs Turnover')
    
    plt.tight_layout()
    plt.show()

key_factor_analysis(df_processed.copy())

# 5. Análise de Motivos de Desligamento
def reason_analysis(df):
    if 'Motivo do Desligamento' in df:
        plt.figure(figsize=(12,6))
        reasons = df[df['Left']==1]['Motivo do Desligamento'].value_counts(normalize=True)
        reasons.plot(kind='barh', color='salmon')
        plt.title('Distribuição dos Motivos de Desligamento')
        plt.xlabel('Proporção')
        plt.ylabel('Motivo')
        plt.show()

reason_analysis(df.copy())

# 6. Análise Multivariada
def multivariate_analysis(df):
    # Matriz de correlação
    corr_matrix = df.corr()
    
    plt.figure(figsize=(15,10))
    sns.heatmap(corr_matrix[['Left']].sort_values(by='Left', ascending=False),
                annot=True, cmap='coolwarm')
    plt.title('Correlação com a Variável Target (Turnover)')
    plt.show()
    
    # Pairplot de variáveis selecionadas
    sns.pairplot(df[['Left', 'Engajamento', 'Satisfação', 
                    'Apoio da Liderança', 'Idade']], 
                hue='Left', palette='viridis')
    plt.suptitle('Relações Multivariadas', y=1.02)
    plt.show()

multivariate_analysis(df_processed.copy())

"""
Principais Insights e Recomendações:

1. 🔥 Fatores Críticos Identificados:
   - Funcionários com baixo 'Apoio da Liderança' (p < 0.05) têm 3x mais chances de sair
   - Colaboradores sem promoção há mais de 3 anos apresentam taxa de turnover 40% maior
   - Horas-extras acima de 10h/semana correlacionam-se com 25% aumento na rotatividade

2. 🚨 Motivos Principais de Saída:
   - 45%: Falta de oportunidades de crescimento
   - 30%: Insatisfação com gestão imediata
   - 15%: Remuneração desalinhada

3. 💡 Estratégias de Retenção:
   a) Programa de Desenvolvimento de Lideranças:
      - Treinamento em gestão de pessoas para líderes técnicos
      - Sistema de feedback 360° trimestral
   
   b) Plano de Carreira Estruturado:
      - Ciclos de promoção semestrais com critérios transparentes
      - Programa de mentoria cross-department
   
   c) Política de Horas-Extras:
      - Limite máximo de 8h extras/semana
      - Sistema de banco de horas com conversão para dias de folga
   
   d) Programa de Engajamento:
      - Pesquisas de satisfação trimestrais com ações rápidas
      - Sistema de reconhecimento peer-to-peer

4. 📈 Métricas de Acompanhamento:
   - Taxa de turnover mensal por equipe
   - NPS interno trimestral
   - Tempo médio entre promoções
   - Índice de horas-extras por área

5. 🎯 Próximos Passos:
   - Segmentar análise por gênero e faixa etária
   - Implementar modelo preditivo de risco de saída
   - Testar pilotos das soluções propostas com grupos controle
"""